### ISSUE TITLE
Build common infrastructure

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#22]
The new website structure should unify the three existing sites: worldwind.arc.nasa.go, goworldwind.org, and webworldwind.org. The content structure, presentation, and look needs to be common. Ensuring the underlying infrastructure of the site supports this goal will facilitate the porting of content from the different sites.

- [x] Clear the current repository and stop automatic updates during new site development (#21)
- [x] Establish site configuration and structure based on current site (#9)
- [x] Create underlying html templates to ease site development and provide common display patterns (#10)
- [x] Enable Travis, wait for Travis deployment until site is finalized (#12)
