### ISSUE TITLE
Restore default Travis CI notifications

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#47]
Restore the Travis CI configurations used by NASA WorldWind projects to the default notification scheme. The original goal of notifying everyone on every build is now unnecessary, as GitHub protected branches and mandatory pull requests ensure that only successful builds make it into the develop and master branches. Removing our custom Travis CI notification blocks has two benefits:.travis.yml is simpler and noisy build notifications stop.

- [x] Restore WebWorldWind (NASAWorldWind/WebWorldWind#162)
- [x] Restore WorldWindAndroid (NASAWorldWind/WorldWindAndroid#123)
- [x] Restore WorldWindJava (NASAWorldWind/WorldWindJava#113)
- [x] Restore WorldWindServerKit (NASAWorldWind/WorldWindServerKit#73)
- [x] Revoke Travis CI builds permission to post at team mailing list, and restore default Google Groups permissions
