### ISSUE TITLE
Migrate to new Hugo based site

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#55]
Complete the migration from the Oracle Jet based site to the new Hugo based site, which includes content from the Oracle Jet site, content from goworldwind.org, and content from webworldwind.org.

- [x] Validate links (#56)
- [x] Ensure content is contained in Hugo static resources (#61)
- [x] Per-project API documentation links (#57)
- [x] Update README to reflect latest design and structure (#65)
- [x] Layout and image adjustments (#58)
- [x] WebStorm project (#59)
- [x] Hugo site link adjustments (#77)
- [x] Prepare Apache for transition to new Hugo based site (#73)
- [x] Travis CI deployment from develop branch (#12)

**Comment by pdavidc** [comment]
Site migration completed on August 7, 2017 at 13:17 Pacific.
