### ISSUE TITLE
Hosted per-project API documentation

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#60]
Establish hosted per-project API documentation on each project's gh-pages branch. Push an initial static site containing API docs from the develop branch. Configure Travis CI to automatically build and push API docs on each push to develop.

- [x] Initial WebWorldWind API docs (NASAWorldWind/WebWorldWind#165)
- [x] Initial WorldWindAndroid API docs (NASAWorldWind/WorldWindAndroid#125)
- [x] Initial WorldWindJava API docs (NASAWorldWind/WorldWindJava#116)
- [x] Evaluate need for WorldWindServerKit hosted docs(NASAWorldWind/WorldWindServerKit#80)
